name = "Zzo"
description = "Hugo blog theme with rich features."
homepage = "https://zzo-docs.vercel.app/zzo"
license = "MIT"
licenselink = "https://github.com/wjb375445/myblog/blob/master/LICENSE.md"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "simple", "light", "dark", "mobile", "gallery", "technical", "fast", "presentation"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "subtheme", "gallery", "technical", "fast", "presentation"]
min_version = "0.65.0"

[author]
  name = "wangjinbao"
  homepage = "https://zzossig.io"