[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "文章"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "项目"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "作品"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "内容"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "图片"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "展示"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "发表"
  url = "publication"
  weight = 7